server:
  port: 80
  servlet:
    context-path:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  tomcat:
    uri-encoding: UTF-8
mybatis:
  base-packages: com.moran.mapper
  type-aliases-package: com.moran.model
  mapper-locations: classpath:mapper/*.xml
mapper:
  not-empty: false
  identity: MYSQL
  mappers: com.moran.util.MyMapper


pagehelper:
  # 分页使用的数据库
  helper-dialect: mysql
  # 分页合理化 true: pageNum <=0 返回第一页, pageNum>总页数 返回最后一页, false: 根据参数查询
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

spring:
  profiles:
    active: dev
  cache:
    type: redis
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write_dates_as_timestamps: false
    time-zone: GMT+8
    default-property-inclusion: non_null
############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: Authorization
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  active-timeout: 2592000
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: random-128
  # 是否输出操作日志
  is-log: false
  # 是否输出打印
  is-print: false
secure:
  ignore:
    urls:
      - /login